on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run API (dev mode)
        run: npm run dev
        env:
          NODE_ENV: development
